### ISSUE TITLE
From the Unity menu Assets/Open C# Project to open the vs code, two vs code projects pop up.

### ISSUE THREAD

**Issue by hubluesky** [Unity-Technologies/vscode-unity-debug#88] opened 2018-06-01 01:56 UTC
From the Unity menu Assets/Open C# Project to open the vs code, two vs code projects pop up.

**Comment by miniwolf** [comment] 2018-06-01 07:10
There seems to be a mismatch inside of Unity on how double clicking on a script to open the project and how the menu works. For now as a work around, double clicking the script will get what you need, I think?

**Comment by hubluesky** [comment] 2018-06-04 02:32
Double click on the script will open two vs code

**Comment by miniwolf** [comment] 2018-06-04 04:04
Can you give me some information about your system? Version of unity, version of tools? And maybe a small example project with some repro steps?

**Comment by hubluesky** [comment] 2018-06-04 09:30
## Steps to Reproduce (for bugs)


1.Create an empty project
2.Create C# Script
3.Double click to open this script
4.At this time it is possible to open two vscode
5.If you do not open two vscode，create a C# Script again.
6.Double-click to open any script
7.This will open two vscode

## Context





## Your Environment
* VS Code Version used: 1.23.1
* Version of the debugger tool: 2.5.0
* Operating System and version: win10
* Any additional information you think could help

**Comment by miniwolf** [comment] 2018-06-04 09:41
What version of Unity are you using?

**Comment by hubluesky** [comment] 2018-06-05 03:18
unity version: 5.6.2f1

**Comment by miniwolf** [comment] 2018-06-06 07:55
I tried this on 5.6.2f1 and 5.6.5f1, and I cannot reproduce this problem.

**Comment by SirIntruder** [comment] 2018-06-07 09:00
It doesn't really matter which Unity version it is, it is happening on both 2017 and 2018.
Repro 100% for me is 1.) open c# project, 2.) close 3.) open c# project again, it will be doubled, and will continue opening double from now on

**Comment by miniwolf** [comment] 2018-06-07 09:49
Okay maybe I am misunderstanding this. But are we talking about double clicking a script and it will open two vs code windows, or are we talking about using the Assets/Open C# project from the menu?
Because the open c# project from the menu is broken, and is a problem that I am trying to address in the Unity Editor.

**Comment by SirIntruder** [comment] 2018-06-07 10:07
You are definatelly right, open c# project is the problem. Just be aware that once you get vscode into this bugged state, opening scripts through project window will get bugged as well

**Comment by miniwolf** [comment] 2018-06-07 14:27
I see :) So this is a problem within Unity, and not part of this project. I have a bunch of changes within Unity related to how opening c# files are dealt with, and how VS Code is dealt with in general. These changes will be rolled out at some point. It is a bigger process to get that in, but I will put this on the list of changes that needs to happen as well.

**Comment by miniwolf** [comment] 2018-12-17 10:54
Closed as fix has landed in Unity. If anyone keeps experiencing this problem, you may need to upgrade to a newer version of Unity.

**Closed by miniwolf** 2018-12-17 10:54 UTC
