### ISSUE TITLE
Can't debug with 2.7.5 + VS Code 1.43.2 + Unity 2018.4.1f1

### ISSUE THREAD

**Issue by SporeProductions** [Unity-Technologies/vscode-unity-debug#166] opened 2020-03-26 16:31 UTC
Your issue may already be reported!
Please search on the [issue track](https://github.com/Unity-Technologies/vscode-unity-debug/issues) before creating one.

## Expected Behavior

Start unity debugger in VS Code 1.43.2
Press play in Unity
Debugger hooks in
Play until breakpoint triggers
VS Code pauses on breakpoint and
...Code line highlights or other indicator (I forget what it used to do)
...should enable skip/step-over
VS code should show variable values in "watch" panel
Hovering mouse over variables in the code should show their values

## Current Behavior

Start unity debugger in VS Code 1.43.2
Press play in Unity
Debugger hooks in
Play until breakpoint triggers
VS Code pauses on breakpoint and
...No Code line or break point is highlighted.
...Top debugger UI only shows Pause and Stop enabled. The Step into and Step over buttons are not active. They should be.
The Watch panel says no data available for any variable entered.
Hovering the mouse over variables in code does not show any values. It's as if the code is not running.

## Possible Solution

Seems to coincide with the Microsoft C# extension fiasco that happened in the last couple weeks. (They changed extension publisher name)

## Context

Can no longer debug! Simply wanted to watch/inspect some data values. It's completely useless now.

## Your Environment
* Unity Version: 2018.4.1f1
* VS Code Version:  1.43.2
* Version of the debugger tool: 2.7.5
* Operating System and version: Windows 10, 64bit

The changelog says the latest version is 3.0.0 but only 2.7.5 is available via VS Code extensions 

This seems to coincide with the Microsoft C# extension fiasco that happened in the last couple weeks. (They changed extension publisher name). Maybe the debugger hasn't updated to match?

**Comment by jamie-tucker** [comment] 2020-03-26 18:43
I'm running into the same issue.
Debugging worked once for me after installing C# 1.21.15 & Debugger for Unity 2.7.5, but since then I am not able to debug. 

![Screen Shot 2020-03-26 at 14 38 41](https://user-images.githubusercontent.com/1652508/77683903-89130700-6f6f-11ea-9d96-92e60f22ba04.png)
![Screen Shot 2020-03-26 at 14 38 45](https://user-images.githubusercontent.com/1652508/77683905-89130700-6f6f-11ea-9b0f-6fd0c38b842e.png)
The Call stack says `Paused on Breakpoint`, but in the editor the debugger controls reflect the same state paused, and nothing shows up in the Variables or Watch tabs.

**Comment by maggiechen** [comment] 2020-03-26 19:12
Same problem here. Last week I fixed my debugging problems w/ the downgrade steps (install the older .vsix file), but now even those don't work. I have the same version numbers as OP, but I'm on Unity 2018.4.15f1

**Comment by jamie-tucker** [comment] 2020-03-29 21:35
I am able to debug properly by downgrading VS Code to version: 1.42.1.

MacOS: 10.14.6
VS Code: **1.42.1**
C# for Visual Studio Code: 1.21.15
Debugger for Unity: 2.7.5
Unity: 2018.4.11f1

**Comment by scrudgey** [comment] 2020-03-31 04:11
Yes, this is my exact problem.
MacOS: 10.13.6
Unity: 2019.3.5
Visual Studio Code Version: 1.43.2
C# extension: 1.21.15
debugger version: 2.7.5

**Comment by heizmoon** [comment] 2020-03-31 09:11
the same issue.
VS Code: 1.43.2
C# for Visual Studio Code: 1.21.15
Debugger for Unity: 2.7.5
Unity: 2019.2.2f1

**Comment by Chris234k** [comment] 2020-03-31 18:37
I believe I have the same issue. I've noticed this error in the Log(Window) in the Output View. It seems to appear when "Paused On Breakpoint" is displayed in the debug window.

`[2020-03-31 14:31:39.836] [renderer1] [error] Cannot read property 'scheme' of null: TypeError: Cannot read property 'scheme' of null
    at h (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2943:285)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2944:335
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2943:825
    at Array.forEach (<anonymous>)
    at u (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2943:814)
    at Object.t.convertToVSCPaths (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2944:308)
    at u.$acceptDAMessage (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3617:444)
    at g._doInvokeHandler (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3681:363)
    at g._invokeHandler (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3681:55)
    at g._receiveRequest (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3679:739)
    at g._receiveOneMessage (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3678:518)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3676:754
    at c.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:110:24)
    at v.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:382:801)
    at t.PersistentProtocol._receiveMessage (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:387:276)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:384:321
    at c.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:110:24)
    at g.acceptChunk (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:380:306)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:379:657
    at Socket.t (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:390:450)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)`

VS Code Info: 
Version: 1.43.2 (system setup)
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

C#: 1.21.15
Debugger For Unity: 2.7.5
Unity 2018.4.13f1

**Comment by PowerOfCreation** [comment] 2020-04-02 14:25
Same issue as described by @SporeProductions 

Version: 1.43.2 (user setup)
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

C# 1.21.16
Debugger For Unity 2.7.5
Unity 2018.4.19f1

**Comment by miniwolf** [comment] 2020-04-02 14:33
Can people here confirm whether downgrading VSCode to 1.42.1 solves the problem? If that is the case, we need to be in contact with the people on https://github.com/microsoft/vscode to resolve this issue

**Comment by PowerOfCreation** [comment] 2020-04-02 14:40
@miniwolf Yes, I can confirm that this indeed fixes the issue.

**Comment by miniwolf** [comment] 2020-04-02 16:09
He suggests that the issue may have been solved in the newest Insider version of VSCode. Can anyone confirm that? https://code.visualstudio.com/insiders/

**Comment by Dunloop26** [comment] 2020-04-02 19:03
@miniwolf Yes, indeed, working as before

Tried on VS Code Insiders **v1.44.0-insider (system setup)**
Unity Debugger **v2.7.5**
C# **v1.21.16**
Windows 10 **64 bits**
Unity **2018.4.8f1**

Debugger working normally
I'm checking if it fails at some point, it started working again (Like in VS Code before the updates)

**Comment by miniwolf** [comment] 2020-04-02 22:14
@Dunloop26 Unfortunately that is a known bug: https://github.com/Unity-Technologies/vscode-unity-debug/issues/164
I will look into fixing this on Monday.

**Comment by miniwolf** [comment] 2020-04-14 15:08
Closing this as VSCode 1.44 has been released

**Closed by miniwolf** 2020-04-14 15:08 UTC
