### ISSUE TITLE
command 'attach.attachToDebugger' not found

### ISSUE THREAD

**Issue by EvansThomas** [Unity-Technologies/vscode-unity-debug#36] opened 2017-05-18 09:34 UTC
When I run the command "Unity Attach Debugger" from the command palette, I get the error "command 'attach.attachToDebugger' not found".

I can use the debugger fine by simply hitting F5 if only a single Unity instance is open. C# intellisense also works fine.
![unityattachdebugger](https://cloud.githubusercontent.com/assets/451684/26195957/076432bc-3bdb-11e7-9de8-1ea1c7ab0753.png)
![attachtodebuggernotfound](https://cloud.githubusercontent.com/assets/451684/26196107/80ce937c-3bdb-11e7-8ab8-57732063567b.png)

Windows 10
Unity 5.6
VS Code 1.12.2
Mono for Windows (x64) 5.0.0
Debugger for Unity 1.2.0

**Comment by lukaszunity** [comment] 2017-05-18 09:36
Duplicate of #34

**Closed by lukaszunity** 2017-05-18 09:36 UTC
