### ISSUE TITLE
Cannot debug when running multiple Unity processes.

### ISSUE THREAD

**Issue by CoderTiger** [Unity-Technologies/vscode-unity-debug#65] opened 2017-10-27 07:26 UTC
Cannot debug when running multiple Unity processes, also failed by using "Attach to Process Picker".

<img width="621" alt="unity-debug-01" src="https://user-images.githubusercontent.com/872723/32092252-3159d26a-bb2a-11e7-8b82-2e0a22b71eaa.png">

The relevant info,
Unity version 2017.1.1f1 Personal
macOS Sierra version 10.12.6
Visual Studio Code version 1.17.2
Debugger for Unity version 1.2.1

Many Thanks.

**Comment by dbastien** [comment] 2017-11-28 22:05
I have the same issue, and the attach to process picker similarly appears to do nothing for me.

**Comment by lukaszunity** [comment] 2017-12-05 13:03
Duplicate of https://github.com/Unity-Technologies/vscode-unity-debug/issues/54

**Closed by lukaszunity** 2017-12-05 13:03 UTC
