### ISSUE TITLE
Breaking into some methods doesn't work

### ISSUE THREAD

**Issue by Figbash** [Unity-Technologies/vscode-unity-debug#16] opened 2016-09-09 16:51 UTC
Hi, I work on a large project, and the debugging functionality works in most cases, but there are some methods where Code will hit the breakpoint but stepping or looking at variable values will not work.  When you try to expand the "this" object under Argument on the left, the expand arrow will turn into a spinner that never finishes.  If you try to step instead, Code will just will clear the Debug Variables area, but never do anything afterwards.  The only way to continue the game playing in Unity is to press Stop multiple times.

I don't know if it's related, but the methods in question seem to always be coroutines of coroutines of coroutines etc, and they have large stacks.

I am unable to share this project, but I may be able to show some of the breaking code.  I would really like to use Code to debug my projects.

Here is a video of the issue:
[CodeDebug.m4v.zip](https://github.com/Unity-Technologies/vscode-unity-debug/files/464423/CodeDebug.m4v.zip)

**Comment by lukaszunity** [comment] 2016-09-12 06:45
Hi,

Without a small and consistent repro project for this issue, it is unlikely to get fixed. As it is impossible for us to say what the issue is based upon the video. It could be an issue with the debugger client, the Mono runtime or the project, or any combination of these.

I'm closing this issue as there is nothing I can do to address it without a repro project.

**Closed by lukaszunity** 2016-09-12 06:45 UTC

**Comment by Figbash** [comment] 2016-09-12 08:24
That's a shame, I will try to make a project, but I was hoping someone with more knowledge of the extension could try to reproduce it on their end.
It has been occurring since the inception of the plugin on multiple projects on both OS X and windows and across multiple mono versions, so I don't think my project or environment are anything special.
