### ISSUE TITLE
Unable to hook to Unity 2018.1.0b2 (64 bit windows)

### ISSUE THREAD

**Issue by NicholasLebrun** [Unity-Technologies/vscode-unity-debug#71] opened 2018-02-20 15:53 UTC
In Unity 2018.1.0b2 there is a new process called UnityCrashHandler64, this seems to interfere with how the plugin detects which Unity process to hook to. When attempting to start the debugger,  I have the following output :

UnityDebug: Initializing
UnityDebug: Searching for Unity process 'Unity Editor'
UnityDebug: Multiple targets with name 'Unity Editor' running. Unable to connect
UnityDebug: Found Unity process 'Unity Editor (UnityCrashHandler64)' (12996)
UnityDebug: Found Unity process 'Unity Editor (Unity)' (10248)
UnityDebug: Disconnected

It would be great if the extension let me choose which process I want to hook to. I often like to have a reference project and the actual project I am working on opened at the same time in two processes of Unity and the way the extension decides what process to hook to prevents me from doing this and using the debugger.

**Comment by NicholasLebrun** [comment] 2018-02-20 16:05
After updating VS Code I now do see a picker for the process, but none of the choices give an output or actually hook successfully. The list of processes (I tried all 3) :

![image](https://user-images.githubusercontent.com/8606506/36434796-e80f874e-162d-11e8-9bed-f74c0adc49bc.png)

**Comment by smt923** [comment] 2018-02-23 23:23
For what it's worth, this is made even worse now when using Unity Hub :(

> UnityDebug: Multiple targets with name 'Unity Editor' running. Unable to connect
> UnityDebug: Found Unity process 'Unity Editor (Unity Hub)' (11176)
> UnityDebug: Found Unity process 'Unity Editor (Unity)' (6732)
> UnityDebug: Found Unity process 'Unity Editor (Unity Hub)' (8400)
> UnityDebug: Found Unity process 'Unity Editor (Unity Hub)' (6648)
> UnityDebug: Found Unity process 'Unity Editor (UnityCrashHandler64)' `(7356)`

I also don't get any successful debugging from the picker/list, still have to close every process apart from the actual Unity editor to debug with vscode

**Comment by lukaszunity** [comment] 2018-02-28 08:51
Fixed in published 1.3.0 version.

**Closed by lukaszunity** 2018-02-28 08:51 UTC

**Comment by Ghopper21** [comment] 2018-03-01 23:27
In Unity 5.6.3f1, I'm now unable to hook to the Unity Editor. It was working last week so I suspect version 1.3.0 caused a regression with older Unity versions.

When trying to attach, I get the error: "Could not find target name 'Unity Editor'. Is it running?"

**Comment by lukaszunity** [comment] 2018-03-02 07:54
@Ghopper21 I'm unable to reproduce this on macOS and Windows with Unity 5.6.5f1. Have you modified your Unity install in any special way?

**Comment by Ghopper21** [comment] 2018-03-13 19:51
Hi @lukaszunity -- I'm using [this hack](https://bitbucket.org/alexzzzz/unity-c-5.0-and-6.0-integration/src) to get C# 6.0 support (in the older version of Unity that doesn't have it). I know this means that debugging doesn't work on OS X, but until a few weeks ago it was working fine on Windows, no problem attaching nor stepping through code. I could understand if this broke stepping through code, but I don't see how it could break simply attaching to the editor, since it doesn't affect the editor.

Is it worth me trying to install the 1.21 version of the Debugger for Unity extension to see if it works on that version? I see the 1.21 version of the extension is available here but I'm not sure how to build from source. Is there a VSIX release of that version available?

**Comment by Ghopper21** [comment] 2018-03-14 00:35
@lukaszunity -- quick update: I tried with a blank Unity v5.6.3f1 project (without any special C#6 hack) and had the same result -- "Could not find target name 'Unity Editor'. Is it running?"

**Comment by andy-block** [comment] 2018-05-04 12:43
I have similar problems here. I'm developing a multiplayer game, so it's often handy to have to Unity instances running representing different sides of the connection. I'm using Unity 5.6.5f1 with Debugger for Unity 1.3.0 on Mac OS 10.13.4. When I run 'Unity Attach Debugger' in the command palette, it successfully sees the two processes (both show "Unity Editor (Unity)"), but whichever I pick, I get a dialog saying "Multiple targets with name 'Unity Editor (Unity)' running. Unable to connect." The Debug console shows the following:

`
UnityDebug: Initializing
UnityDebug: Searching for Unity process 'Unity Editor (Unity)'
UnityDebug: Multiple targets with name 'Unity Editor (Unity)' running. Unable to connect
UnityDebug: Found Unity process 'Unity Editor (Unity)' (35900)
UnityDebug: Found Unity process 'Unity Editor (Unity)' (10701)
UnityDebug: Disconnected
`

@lukaszunity Any clues what might be going wrong here? Am I using it wrong?

**Comment by miniwolf** [comment] 2018-05-04 12:49
@andy-block this is a limitation of the tool. You could try out this preview release, that has a fix to the problem you are describing. This is also described here: https://github.com/Unity-Technologies/vscode-unity-debug/issues/43

**Comment by andy-block** [comment] 2018-05-04 12:52
Oh wow - thanks for the super-quick response! I'll check that out.
