### ISSUE TITLE
Can't view locals in the watch window (or by hovering the mouse over them)

### ISSUE THREAD

**Issue by RobFireproof** [Unity-Technologies/vscode-unity-debug#15] opened 2016-09-07 09:54 UTC
Using version 1.0.3 with Unity 5.4.0f3, the watch window can't view member variables without "this" specified explicitly (see screenshot attached).
![image](https://cloud.githubusercontent.com/assets/7429371/18307644/2a8e6ba4-74e9-11e6-9364-9cbfd7e1d25f.png)

Stepping through in the debugger, it's hitting the case in UnityDebugSession.cs line 478 where the "Unknown" flag is set. Unfortunately I'm on a deadline so can't investigate further right now (my knowledge of the Mono runtime isn't good, so it'd probably take me a while!).

Rob.

**Comment by lukaszunity** [comment] 2016-09-07 15:29
The issue is that we do not do any analysis of the C# source code and the debugger protocol does not provide it either. So the watch requests are are just passed directly to the Mono debugger and in this case there is no local variable named `LoadRequest` and you need to full type `this.LoadRequest`.

What you can do is right click on locals and select `Add Watch` and that should work.

I will close this issue and I will add it as a feature for our backlog.

**Closed by lukaszunity** 2016-09-07 15:29 UTC

**Comment by CoenraadS** [comment] 2016-11-16 21:14
Is there any ETA on this feature? It would be very useful.

**Comment by lukaszunity** [comment] 2016-11-17 06:24
It is unlikely that we will support hovering over variables, based upon how the current debugger protocol works. I've looked into this feature and the debugger protocol just passes strings and substrings of the text you are hovering over to the debugger extension. This means you need to parse the string you get and guess whether the value is type, local, global, class member, etc. 

For an statement like this

`if(value != 32 && typeof(someType) != MyManager)`

If you hover over `someType` then protocol might pass the string `if(value != 32 && typeof(someType` to the debugger. Parsing this string correctly in the debugger extension and always providing the correct results is very hard. 

If the debugger protocol some day will work together with the C# parsing and just provide the exact expression that need to be evaluated, which would be the ideal solution, then we could very easily support this feature.

**Comment by toxikman** [comment] 2016-12-13 02:52
Perhaps you could evaluate the expression and if it's a symbol (variable or method name) and it's not able to be evaluated then you append "this." to the string and evaluate it again?
