### ISSUE TITLE
Can't debug breakpoints at function calls that originated from unity.ui actions

### ISSUE THREAD

**Issue by eladleb** [Unity-Technologies/vscode-unity-debug#160] opened 2020-03-13 18:16 UTC
## Expected Behavior
When pressing a button that calls a function and has a breakpoint set in it - The debugger should gain focus and highlight the current execution row

## Current Behavior
The debugger doesn't gain focus and thread#1 appears to be running, although Unity Editor is waiting for the debugger.

## Additional info:
- It started happening a few days ago when I had to downgrade VS Code's omnisharp extension.
- Debugging non-ui related functions (start / update) in VS Code works as expected.
- Debugging all functions in Visual Studio 2019 for mac works as expected.
- Tried uninstalling and reinstalling every mentioned component.

## Steps to Reproduce (for bugs)
1. To fully understand what happens: [screencap](https://youtu.be/j2AwngnFmMU)
2. I've attached the sample project show in the above [Sample Project](https://github.com/Unity-Technologies/vscode-unity-debug/files/4330929/vscode-debug-notworking.zip)

## Context
This makes working with VS Code and the unity debugger impossible, I'd love to understand if there is a solution for this. I assume it's an environment issue but unsure what to uninstall / reinstall

## Your Environment
* Unity Version: 2019.3.5
* VS Code Version: 1.43.0
* Version of the debugger tool: 1.7.2 & 1.7.3
* Operating System and version: Mac OS, 10.15.3 
* Tried both mono 6.4.0 and 6.6.0
* Tried both the latest omnisharp vs-code-debugger compatible version (csharp-1.21.12) and the one after the name change: ms-dotnettools.csharp-1.21.14 (with unity debugger 1.7.3)

**Comment by miniwolf** [comment] 2020-03-16 08:57
This seems to be an old known problem, I will put it on the backlog.
If you want to dig into it yourself and suggest a fix, you can compile the plugin yourself and see what is going on. https://github.com/Unity-Technologies/vscode-unity-debug/wiki/Development-setup

**Comment by eladleb** [comment] 2020-03-16 11:05
Thanks @miniwolf , 
I spent quite a few hours this morning just trying to get the plugin to run so I can look into it, but couldn't make it run properly :(
I wonder if it's not working because I'm on OSX since I did go through the dev-setup steps over and over...

**Comment by miniwolf** [comment] 2020-03-16 11:12
What issues are you running into?

**Comment by eladleb** [comment] 2020-03-16 11:56
This is what I get when trying to build DTestApp and every other target in the TestProjects:

/Library/Frameworks/Mono.framework/Versions/6.6.0/lib/mono/xbuild/Microsoft/Microsoft.NET.Build.Extensions/Microsoft.NET.Build.Extensions.ConflictResolution.targets(5,5): Error NETSDK1052: Framework list file path 'C:/projects/mono/mono/build/builds/monodistribution/lib/mono/4.5/RedistList/FrameworkList.xml' is not rooted. Only full paths are supported. (NETSDK1052) (DTestApp)

And I also got an error on a validation on not finding "Mono.Posix.5.4.0.201\build\net45\Mono.Posix.targets"

So I removed the validation line (since the file exists in the path). It ignored the issue, though I'm unsure if it's a valid solution.

I was able to run the makefile and generate a vsix though...

To be honest, even if it ran properly, I'm a little unsure of how to properly start the process of finding the issue. 
While I'm knowledgeable when it gets debugging tools and even some command-line debug tools I've never actually debugged a debugger process. Using only the existing documentation, it will be quite a challenge.

**Comment by Romeno** [comment] 2020-03-16 13:34
Unity Version: 2017.4.28
VS Code Version: 1.43.0
Unity Debugger version: 2.7.2 (tried 2.7.3, 2.7.4)
C# for Visual Studio Code version: 1.21.12 (tried 1.21.13, 1.21.14)
Operating System and version: Mac OS, 10.14.6

**Comment by miniwolf** [comment] 2020-03-16 15:32
Building the Test applications require that you have a locale clone of mono, as it depends on a mono runtime to run. These things will hopefully change, as they are quite difficult to maintain. A CI to run them continuously would also be great.

But back to how to debug this. I have a few note on the same wiki page, "inceptious debugging". But it will require a bit of digging.

**Comment by eladleb** [comment] 2020-03-16 19:00
Oh, got it...
Unfortunately I don't see how I'll be able to allocate enough time to properly get into it and still meet our studio's tight deadlines...

I ended up switching to the cumbersome and unpleasant Visual Studio 2019 for mac for now :(

**Comment by eladleb** [comment] 2020-03-19 13:17
From my external investigation, if I set a breakpoint at **UnityEngine.UI.Button** class, it behaves properly for a moment.

(/Applications/Unity/Hub/Editor/2019.3.5f1/Unity.app/Contents/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/UI/Core/button.cs)

Once we step to the Invoke action, the debugger gets stuck.

```
        private void Press()
        {
            if (!IsActive() || !IsInteractable())
                return;

            UISystemProfilerApi.AddMarker("Button.onClick", this);
            **m_OnClick.Invoke();**
        }
```
I wonder if this issue is related to the recently updated Unity UI (com.unity.ugui). It used to run perfectly a couple of weeks ago.

**Comment by roland-quiros-wf** [comment] 2020-03-19 20:06
I've been seeing the same thing in 2018.4.11f1 and 2018.4.5f1 ever since the OmniSharp package name shakeup, so I'm not sure if a UGUI update's the culprit here. I've experienced it before, as @miniwolf mentioned, but nowhere as consistently as post-csharp-1.21.12.

**Comment by Anheurystics** [comment] 2020-03-19 23:20
I managed to repro this issue as well on Unity 2018.4.15f1, and I noticed that it happens no matter what C#/Debugger extension combination I reverted to (even using versions before the name change, it happened to me).

The kind of issue I'm experiencing is that, with a breakpoint in an OnEnable function, it breaks into properly once Play mode is entered, but doesn't break into properly one the GameObject/Component is disabled/re-enabled (the Editor freezes, but the VS Code instance doesn't gain focus and the line number isn't highlighted)

I managed to find out using VS Code's Developer Tools console that this error message appears when such a freeze happens:

```js
  ERR Cannot read property 'scheme' of null: TypeError: Cannot read property 'scheme' of null
    at h (file:///%LOCALAPPDATA%/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2943:285)
    at file:///%LOCALAPPDATA%/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2944:335
    at file:///%LOCALAPPDATA%/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2943:825
    at Array.forEach (<anonymous>)
    at u (file:///%LOCALAPPDATA%/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2943:814)
    at Object.t.convertToVSCPaths (file:///%LOCALAPPDATA%/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2944:308)
    at u.$acceptDAMessage (file:///%LOCALAPPDATA%/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3617:444)
    at g._doInvokeHandler (file:///%LOCALAPPDATA%/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3681:363)
    at g._invokeHandler (file:///%LOCALAPPDATA%/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3681:55)
    at g._receiveRequest (file:///%LOCALAPPDATA%/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3679:739)
    at g._receiveOneMessage (file:///%LOCALAPPDATA%/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3678:518)
    at file:///%LOCALAPPDATA%/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3676:754
    at c.fire (file:///%LOCALAPPDATA%/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:110:24)
    at v.fire (file:///%LOCALAPPDATA%/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:382:801)
    at t.PersistentProtocol._receiveMessage (file:///%LOCALAPPDATA%/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:387:276)
    at file:///%LOCALAPPDATA%/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:384:321
    at c.fire (file:///%LOCALAPPDATA%/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:110:24)
    at g.acceptChunk (file:///%LOCALAPPDATA%/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:380:306)
    at file:///%LOCALAPPDATA%/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:379:657
    at Socket.t (file:///%LOCALAPPDATA%/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:390:450)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Potential temporary fix?**: I tried downgrading to VS Code 1.42.1, and breakpoints now break properly. I'm guessing this is an issue with the latest VS Code update? When I do this, I notice this error message instead in the Developer Tools:
```
Extension is not compatible with Code 1.42.1. Extension requires: ^1.43.0
```

So some additional investigation is needed.

**Comment by eladleb** [comment] 2020-03-20 16:04
Thanks @Anheurystics ,  

I can confirm that the debugger works as expected with the following downgraded setup:
Visual Studio Code - 1.42.1
Extension: C# for Visual Studio Code (ms-vscode) - 1.21.12
Extension: Debugger for Unity (unity.unity-debug) - 2.7.2

BTW, I'm using Mac OS 10.15.3, Unity 2019.3.5 with Visual Studio Code Editor plugin 1.2.0 though I'm also of the opinion that the main culprit is most likely the recent VS Code update.

**Comment by mcaisw** [comment] 2020-03-26 02:28
same problem

**Comment by EthanSK** [comment] 2020-03-27 14:37
same problem

**Comment by weinand** [comment] 2020-04-02 16:31
The crash mentioned above is https://github.com/microsoft/vscode/issues/93223 which has been fixed 10 days ago.

Could you please try whether the problem is fixed in latest Insiders.

**Comment by roland-quiros-wf** [comment] 2020-04-03 21:01
Not an exhaustive test by any means, but I've had luck so far getting button-invoked breakpoints to trigger, with full step control, in Unity 2018.4.11f1 and 2018.4.5f1, with 1.44-insider. I'm using C# 1.21.16, with Unity Debugger 2.7.5.

@weinand, am I correct in reading that the fix should hit mainline on April 8?

**Comment by weinand** [comment] 2020-04-04 00:22
The fix is in Insiders which will become Stable sometime next week.

**Comment by miniwolf** [comment] 2020-04-14 15:09
Closing this as VSCode 1.44 has been released

**Closed by miniwolf** 2020-04-14 15:09 UTC
Labels: bug
